version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8989
    volumes:
      - .:/code
    ports:
      - "8989:8989"
    depends_on:
      - db
      - migrate
  db:
    image: postgres
  migrate:
    build: .
    command: python manage.py migrate

